name: 📦 Build & Deploy Next.js Portfolio

# 1. Trigger on push to main or manual dispatch
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# 2. Required token permissions
permissions:
  contents: read    # for checkout
  pages: write      # to publish to GitHub Pages
  id-token: write   # for OIDC if ever needed

# 3. Prevent overlapping deploys
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 3.1 Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4

      # 3.2 Configure Pages (injects static export & disables image API)
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      # 3.3 Setup Node.js with caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 3.4 Install deps
      - name: Install dependencies
        run: npm ci

      # 3.5 Build the static export (`out/`)
      - name: Build site
        run: npm run build

      # 3.6 Upload the static artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      # 4.1 Deploy to the github-pages environment
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
